DELETE FROM DATA_WAREHOUSE_Layer.dbo.FACT_DIGITAL_PROFILES;
DELETE FROM DATA_WAREHOUSE_Layer.dbo.DIM_TRANSACTIONS;
DELETE FROM DATA_WAREHOUSE_Layer.dbo.DIM_TRANSACTION_TYPE;
DELETE FROM DATA_WAREHOUSE_Layer.dbo.DIM_POST_EKYC;
DELETE FROM DATA_WAREHOUSE_Layer.dbo.DIM_EKYC;
DELETE FROM DATA_WAREHOUSE_Layer.dbo.DIM_CRM;
DELETE FROM DATA_WAREHOUSE_Layer.dbo.DIM_ACCOUNTS;
 
DELETE FROM STAGING_Layer.dbo.STAGING_Post_eKYC_Information;
DELETE FROM STAGING_Layer.dbo.STAGING_eKYC_Information;
DELETE FROM STAGING_Layer.dbo.STAGING_Digital_Transaction;
DELETE FROM STAGING_Layer.dbo.STAGING_Digital_Account;
DELETE FROM STAGING_Layer.dbo.STAGING_CRM;

